<?php
/**
 * Subiz Live Chat Extension
 *
 * @category Subiz
 * @package Subiz_LiveChat
 * @copyright Copyright (c) 2015 Subiz, Inc. (http://www.subiz.com)
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @version 1.0.0 
 */
?>

<div class="content-header">
  <table cellspacing="0">
    <tbody>
      <tr>
        <td><h3>Subiz Dashboard Integration</h3></td>
      </tr>
    </tbody>
  </table>
</div>

<iframe id="subiz_dashboard" src="https://dashboard.subiz.com"></iframe>